spring:
  profiles:
    active: dev

#camel.springboot.shutdownTimeout: 2

camel:
  springboot:
    shutdownTimeout: 2
    health.indicator.enable: true

management:
  security:
    enabled: false
---

spring:
  profiles: mock
  mail:
      host: smtp.gmail.com
      port: 587
      username: <<GMAIL Account User Name>>
      password: <<Add Password>>
      properties.mail.smtp.auth: true
      properties.mail.smtp.starttls.enable: true

mailTo: <<Provide Gmail Address from alert email Should be sent>>
mailFrom: <<Provide Gmail Address where alert email sholud be received>>



startRoute: direct:inputDirect
#Need to keep it since it was refer into the route, so runtime Camel Expect this value to be presented in profile
fromRoute: file:data/dev/input?delete=true&readLock=none&moveFailed=error
toRoute1: mock:outputMock
tojdbcRoute: mock:outputMock1
toSuccessRoute: mock:outputMock2
healthCheckRoute: direct:healthCheck


message: Mock Environment!!

---

spring:
  profiles: dev
  datasourceConnInfo:
    driver-class-name: org.postgresql.Driver
            #Updated localdb to localdbDeleteMe to generate the exception to validate the health route.
            #url: jdbc:postgresql://localhost:5432/localdbDeleteMe
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
      username: <<GMAIL Account User Name>>
      password: <<Add Password>>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    packages.trust-all: true
        #In order to test select node response list in test cases, add packages.trust-all: true in application.yml
                 #    - Recent camel version security has been updated, so add "packages.trust-all: true" in application.yml

mailTo: <<Provide Gmail Address from alert email Should be sent>>
mailFrom: <<Provide Gmail Address where alert email sholud be received>>

fromRoute: activemq:inputItemQueue
toRoute: log:?level=INFO&showBody=true
tojdbcRoute: jdbc:myDataSource
toErrorQueue: activemq:errorItemQueue
toSuccessRoute: file:data/dev/output?fileName=SuccessMessage.txt
healthCheckRoute: timer:healthCheckTimer?period=25s
toSQLNode: sql:select * from ITEMS where sku = :#skuId?dataSource=#myDataSource

message: DEV Environment!!

---

spring:
  profiles: stage
  datasourceConnInfo:
    driver-class-name: org.postgresql.Driver
            #Updated localdb to localdbDeleteMe to generate the exception to validate the health route.
            #url: jdbc:postgresql://localhost:5432/localdbDeleteMe
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: <<GMAIL Account User Name>>
    password: <<Add Password>>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    packages.trust-all: true


mailTo: <<Provide Gmail Address from alert email Should be sent>>
mailFrom: <<Provide Gmail Address where alert email sholud be received>>

fromRoute: activemq:inputItemQueue
toRoute: log:?level=INFO&showBody=true
tojdbcRoute: jdbc:myDataSource
toErrorQueue: activemq:errorItemQueue
toSuccessRoute: file:data/dev/output?fileName=SuccessMessage.txt
healthCheckRoute: timer:healthCheckTimer?period=25s

message: Stage Environment!!

---

spring:
  profiles: prod
  datasourceConnInfo:
    driver-class-name: org.postgresql.Driver
            #Updated localdb to localdbDeleteMe to generate the exception to validate the health route.
            #url: jdbc:postgresql://localhost:5432/localdbDeleteMe
    url: jdbc:postgresql://localhost:5432/localdb
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: <<GMAIL Account User Name>>
    password: <<Add Password>>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    packages.trust-all: true

mailTo: <<Provide Gmail Address from alert email Should be sent>>
mailFrom: <<Provide Gmail Address where alert email sholud be received>>

fromRoute: activemq:inputItemQueue
toRoute: log:?level=INFO&showBody=true
tojdbcRoute: jdbc:myDataSource
toErrorQueue: activemq:errorItemQueue
toSuccessRoute: file:data/dev/output?fileName=SuccessMessage.txt
healthCheckRoute: timer:healthCheckTimer?period=25s


message: Production Environment!!
---